spring.application.name=notification-service
server.port=8087

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

# Email Verification Kafka Topic Configuration
kafka.topics.email-verification=email-verification-topic

# ===============================
# Email Configuration
# ===============================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=mohab
spring.mail.password=123456
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs