version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-user-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3326:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql